package com.linh.apps.cms_movie.dao;

import com.linh.apps.cms_movie.bean.Movie;
import com.linh.apps.cms_movie.bean.MovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    long countByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int deleteByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int insertSelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    List<Movie> selectByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    Movie selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int updateByExample(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int updateByPrimaryKeySelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_movie
     *
     * @mbg.generated Thu Mar 19 14:37:05 CST 2020
     */
    int updateByPrimaryKey(Movie record);
}