package com.linh.apps.cms_movie.dao;

import com.linh.apps.cms_movie.bean.User_Role;
import com.linh.apps.cms_movie.bean.User_RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    long countByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int deleteByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int insert(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int insertSelective(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    List<User_Role> selectByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    User_Role selectByPrimaryKey(Long id);
    List<User_Role> selectByUserId(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") User_Role record, @Param("example") User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int updateByExample(@Param("record") User_Role record, @Param("example") User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int updateByPrimaryKeySelective(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    int updateByPrimaryKey(User_Role record);
}