package com.linh.apps.cms_movie.bean;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_role.id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_role.name
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_role.id
     *
     * @return the value of cms_role.id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_role.id
     *
     * @param id the value for cms_role.id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_role.name
     *
     * @return the value of cms_role.name
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_role.name
     *
     * @param name the value for cms_role.name
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}