package com.linh.apps.cms_movie.bean;

public class User_Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.user_id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.role_id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.id
     *
     * @return the value of cms_user_role.id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.id
     *
     * @param id the value for cms_user_role.id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.user_id
     *
     * @return the value of cms_user_role.user_id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.user_id
     *
     * @param userId the value for cms_user_role.user_id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.role_id
     *
     * @return the value of cms_user_role.role_id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.role_id
     *
     * @param roleId the value for cms_user_role.role_id
     *
     * @mbg.generated Wed Mar 11 18:14:01 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}